#
# Dev Services (PostgreSQL) - reproducible
#
%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.devservices.db-name=fsi_payments
%dev.quarkus.datasource.devservices.username=payments
%dev.quarkus.datasource.devservices.password=payments
%dev.quarkus.datasource.devservices.port=54321
%dev.quarkus.datasource.devservices.reuse=true

# Para que el schema no se borre en cada restart (y los datos seed queden estables)
%dev.quarkus.hibernate-orm.schema-management.strategy=update
%dev.quarkus.hibernate-orm.log.sql=true