quarkus.hibernate-orm.persistence-unit-name=fsiPaymentsPU
quarkus.jms.connection-factory=java:/JmsXA
quarkus.jms.queue.payment-queue=queue/paymentQueue
quarkus.hibernate-orm.hbm2ddl.auto=create
quarkus.log.category."org.hibernate.SQL".level=DEBUG