server.port=8082
spring.application.name=fsi-inventory-springboot2-legacy

spring.datasource.url=jdbc:h2:mem:inventory;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Workaround típico en apps que usan Springfox + Spring Boot 2.6/2.7
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

management.endpoints.web.exposure.include=health,info,metrics,env

# Credenciales hardcodeadas (intencional para que aparezcan hallazgos de seguridad)
inventory.admin.user=admin
inventory.admin.password=admin123

