create table products (
  id bigint generated by default as identity primary key,
  sku varchar(64) not null,
  name varchar(256) not null,
  quantity integer not null,
  updated_at timestamp not null
);

create unique index ux_products_sku on products (sku);

insert into products (sku, name, quantity, updated_at) values
  ('ACME-001', 'Acme Anvil', 10, current_timestamp),
  ('ACME-002', 'Acme Rocket Skates', 3, current_timestamp);

